version: '3.8'

services:
  scada_be:
    build: .
    image: scada_be
    container_name: scada_be
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    depends_on:
      - timescaledb
      - redis
    networks:
      - intra-domain
    volumes:
      - ./log:/app/log
      - ./firmware_files:/app/firmware_files

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: scada-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scada_db
    volumes:
      - timescale_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - intra-domain

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - timescaledb
    networks:
      - intra-domain

  redis:
    image: redis:alpine
    container_name: scada_redis
    ports:
      - "6379:6379"
    networks:
      - intra-domain

volumes:
  timescale_data:

networks:
  intra-domain: