version: '3.8'

services:
  scada_be:
    build: .
    image: scada_be:1.1.1
    container_name: scada_be
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
    env_file:
      - .env.local
    depends_on:
      - timescaledb
      - redis
    networks:
      - intra-domain
    volumes:
      - ./log:/app/log
      - ./firmware_files:/app/firmware_files

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: scada-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scada_db
    volumes:
      - timescale_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - intra-domain

  redis:
    image: redis:alpine
    container_name: scada_redis
    ports:
      - "6379:6379"
    networks:
      - intra-domain

  # app:
  #   image: scada_fe:1.1.0  # Replace with your built image name
  #   container_name: scada_fe
  #   # build:
  #   #   context: .  # Path to your Dockerfile
  #   #   dockerfile: Dockerfile
  #   env_file:
  #     - .env.local  # Path to your .env file
  #   ports:
  #     - "80:80" # Expose port 80 on the host to port 80 in the container
  #   restart: unless-stopped  # Restart policy
  #   depends_on:
  #     - scada_be

  #   networks:
  #     - intra-domain
  
volumes:
  timescale_data:

networks:
  intra-domain: