version: '3.8'

services:
  scada_backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
  
  timescaledb:
    image:  timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scada_db
      volumes:
      - timescale_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - timescaledb

volumes:
  timescale_data:
