"""add Task model

Revision ID: 11f7c3f0b6bf
Revises: 761334764f60
Create Date: 2024-10-31 15:54:20.193504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f7c3f0b6bf'
down_revision: Union[str, None] = '761334764f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DISCONNECTION', 'POWERLOST', 'REPAIR', name='tasktype'), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['account.user_id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('time')
    )
    op.create_index(op.f('ix_audit_action'), 'audit', ['action'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_action'), table_name='audit')
    op.drop_table('tasks')
    # ### end Alembic commands ###
