"""Add audit Table

Revision ID: 2fd818f08390
Revises: 01a1fefe15bc
Create Date: 2024-10-13 20:33:20.073172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd818f08390'
down_revision: Union[str, None] = '01a1fefe15bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'READ', name='actionenum'), nullable=False),
    sa.Column('details', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account.user_id'], ),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_index(op.f('ix_audit_action'), 'audit', ['action'], unique=False)
    op.add_column('status', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('status', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('units', sa.Column('toggle', sa.Boolean(), nullable=True))
    op.add_column('units', sa.Column('on_time', sa.Time(), nullable=False))
    op.add_column('units', sa.Column('off_time', sa.Time(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'off_time')
    op.drop_column('units', 'on_time')
    op.drop_column('units', 'toggle')
    op.drop_column('status', 'longitude')
    op.drop_column('status', 'latitude')
    op.drop_index(op.f('ix_audit_action'), table_name='audit')
    op.drop_table('audit')
    # ### end Alembic commands ###
