"""Optimize the models

Revision ID: 4a4661a9f2b0
Revises: 5a5512188797
Create Date: 2024-10-19 12:23:59.728892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a4661a9f2b0'
down_revision: Union[str, None] = '5a5512188797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clusters_account_id_fkey', 'clusters', type_='foreignkey')
    op.drop_column('clusters', 'account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('clusters_account_id_fkey', 'clusters', 'account', ['account_id'], ['user_id'])
    # ### end Alembic commands ###
