"""Optimize Unit table, add mac address

Revision ID: 761334764f60
Revises: 4a4661a9f2b0
Create Date: 2024-10-20 18:51:51.036153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761334764f60'
down_revision: Union[str, None] = '4a4661a9f2b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('mac', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'units', ['mac'])
    op.drop_column('units', 'latitude')
    op.drop_column('units', 'address')
    op.drop_column('units', 'longitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('units', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('units', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'units', type_='unique')
    op.drop_column('units', 'mac')
    # ### end Alembic commands ###
