"""Add role

Revision ID: 7df3424e56cc
Revises: 0fd53c3ee31b
Create Date: 2024-10-13 10:13:32.821299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7df3424e56cc'
down_revision: Union[str, None] = '0fd53c3ee31b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_index(op.f('ix_role_role_id'), 'role', ['role_id'], unique=False)
    op.add_column('account', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('account', sa.Column('updated', sa.DateTime(), nullable=False))
    op.add_column('account', sa.Column('role', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'account', 'role', ['role'], ['role_id'])
    op.drop_column('account', 'Date_created')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('Date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'role')
    op.drop_column('account', 'updated')
    op.drop_column('account', 'created')
    op.drop_index(op.f('ix_role_role_id'), table_name='role')
    op.drop_table('role')
    # ### end Alembic commands ###
