"""Add rank to account

Revision ID: a9c3afd93c96
Revises: 93e0c6ca17cc
Create Date: 2024-11-07 07:53:05.238094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c3afd93c96'
down_revision: Union[str, None] = '93e0c6ca17cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('role', sa.Column('rank', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'rank')
    # ### end Alembic commands ###
