"""Update Status Table

Revision ID: ccb42477209e
Revises: 1318ab288f34
Create Date: 2024-10-14 21:37:05.175694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccb42477209e'
down_revision: Union[str, None] = '1318ab288f34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('toggle', sa.Boolean(), nullable=True))
    op.add_column('status', sa.Column('power_factor', sa.Float(), nullable=True))
    op.add_column('status', sa.Column('frequency', sa.Float(), nullable=True))
    op.add_column('status', sa.Column('total_energy', sa.Float(), nullable=True))
    op.drop_column('status', 'alive')
    op.drop_column('status', 'latitude')
    op.drop_column('status', 'longitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('status', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('status', sa.Column('alive', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('status', 'total_energy')
    op.drop_column('status', 'frequency')
    op.drop_column('status', 'power_factor')
    op.drop_column('status', 'toggle')
    # ### end Alembic commands ###
